site_name: GRC Engineering
site_url: https://grc.engineering
plugins:
  - privacy
theme: 
  name: material
  font: 
    text: Manrope
    code: Consolas
  palette:
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference