site_name: "GRC Engineering"
site_url: https://grc.engineering
repo_url: https://github.com/grcengineering/grcengineering.github.io
repo_name: grcengineering
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - privacy
  - search
  - social:
      cards_layout_options:
        font_family: IBM Plex Mono
        background_color: "#1b95c1ff"
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: grcengineering/grcengineering.github.io
      branch: main
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/12997229/
    - icon: fontawesome/brands/github
      link: https://github.com/grcengineering
    - icon: fontawesome/brands/slack
      link: https://grcengineering.slack.com
theme:
  name: material
  font: 
    text: Roboto Mono
    code: Consolas
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  palette:
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: grcengineering-light
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: grcengineering-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: grcengineering-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference